# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'docker-container:$(build.buildId)'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'romans/TestsExam/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
  displayName: 'Running tests'
 
- script: dotnet test romans/TestsExam --logger trx --collect "Code coverage"
  displayName: 'Get tests results'
  
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'Publish tests results'
  
- script: dotnet tool install --global coverlet.console
  displayName: 'Installing Coverlet'
  
- script: dotnet add romans/TestsExam package coverlet.msbuild
  displayName: 'Adding coverlet package to Test project'
  
- script: dotnet test romans/TestsExam /p:CollectCoverage=true /p:CoverletOutputFormat='cobertura' /p:CoverletOutput='/coverage.cobertura.xml'
  displayName: 'Output code review'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: '/coverage.cobertura.xml'
  displayName: 'Publish code coverage'
  
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker build'